goserver:
  build: ./go/
  working_dir: /go/src/a-simple-chatting-server
  command: go run ./src/go/entrypoint.go
  volumes:
    - $GOPATH/src/a-simple-chatting-server:/go/src/a-simple-chatting-server
  ports:
    - 8091:8091
  links:
    - mysql
    - phpmyadmin
mysql:
  image: mysql:latest
  volumes:
    - ../db:/data
  environment:
    MYSQL_ROOT_PASSWORD: root
  ports:
    - 3306:3306
phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  ports:
    - 8080:80
  links:
    - mysql:db
